# Generated by Django 3.1.6 on 2021-02-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='satellite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='shipid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
